# Generated by Django 4.1.7 on 2024-10-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_analysisfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisfile",
            name="input_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="analysisfile",
            name="output_data",
            field=models.JSONField(default=dict),
        ),
    ]
